name = "sink"
main = "backend/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sink_db"
database_id = "8e98bba8-625a-4f0b-b9eb-5159f365e557"
